version: "2.1"

services:

   letsencrypt-proxy:
     image: linuxserver/letsencrypt
     restart: always
     ports:
       - 80:80
       - 443:443
     volumes:
       - ./config/letsencrypt:/config
     environment:
       - EMAIL=lucamontechiesi@gmail.com
       - URL=lumontec.com
       - SUBDOMAINS=blog
       - VALIDATION=http
       - TZ=Europe/Stockholm
       - PUID=1000
       - PGID=1000

   blog-lumontec:
     build: . 
     ports:
      - "8000:3000"
     restart: always
